import '/shared/vgv-command.js?v=20260821-6';
if(window.self!==window.top)document.documentElement.classList.add('embedded');
const API='https://permuta-api.vgventures.com.br',IMAGE_HOSTS=new Set(['imgbr.imovelwebcdn.com','si9dados3.com.br','cdn.fullbroker.com.br']);
const parameters=new URLSearchParams(location.search);
const state={offset:0,limit:20,lastRequest:null,data:null,preview:null,locations:null,mode:parameters.get('mode')||'search',tenantId:parameters.get('tenantId'),saved:[],permissions:new Set()};
const $=(selector,root=document)=>root.querySelector(selector);
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=String(text);return node;}
function finite(value){const number=Number(value);return value!==null&&value!==''&&Number.isFinite(number)?number:null;}
const money=(value)=>finite(value)===null?'Desconhecido':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(value);
const integer=(value)=>finite(value)===null?'Desconhecido':new Intl.NumberFormat('pt-BR').format(value);
function safeUrl(value){try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password?url.href:null;}catch{return null;}}
function safeImage(value){const url=safeUrl(value);return url&&IMAGE_HOSTS.has(new URL(url).hostname.toLowerCase())?url:null;}
async function api(path,options={}){let response;try{response=await fetch(`${API}${path}`,{credentials:'include',method:options.method||'GET',headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{})},body:options.body?JSON.stringify(options.body):undefined});}catch{throw new Error('Não foi possível conectar ao serviço.');}let data=null;try{data=await response.json();}catch{}if(!response.ok){const value=data?.error,error=new Error(value?.message||value||`Erro ${response.status}`);error.code=value?.code;error.status=response.status;throw error;}return data;}
function finderPath(path=''){return state.tenantId?`/api/v1/tenants/${encodeURIComponent(state.tenantId)}/finder${path}`:`/api/v1/market/finder${path}`;}
function exchangePath(path){return state.tenantId?`/api/v1/tenants/${encodeURIComponent(state.tenantId)}/exchange${path}`:path;}
function structuredCriteria(){const {keyword,...criteria}=state.data?.criteria||{};return criteria;}
function setStatus(message,error=false){const box=$('#status');box.textContent=message;box.classList.toggle('error',error);}
function enrichmentStatus(data){return {queued:' Atualização das fontes aprovada e agendada; novos anúncios aparecerão nas próximas buscas.',pending:' A atualização das fontes está aguardando processamento ou já está em andamento.',fresh:' Ao menos uma fonte aprovada foi consultada com sucesso nas últimas 6 horas.',unavailable:' A última atualização das fontes falhou ou o agendamento está temporariamente indisponível.'}[data.enrichment?.status]||'';}
function setBusy(busy){document.querySelectorAll('button').forEach((button)=>{if(button.id!=='logout')button.disabled=busy;});}

async function boot(){try{if(state.tenantId){const session=await api('/api/v1/session');if(session.authenticated&&session.memberships?.some((item)=>item.tenantId===state.tenantId)){const capabilities=await api(`/api/v1/tenants/${encodeURIComponent(state.tenantId)}/capabilities`);state.permissions=new Set(capabilities.permissions||[]);return showApp();}throw new Error('Sua sessão não possui acesso a esta organização.');}if((await api('/session')).authenticated)return showApp();}catch(error){if(state.tenantId)$('#login-error').textContent=`${error.message} Entre novamente pelo Painel VGV.`;}$('#login').hidden=false;}
async function showApp(){$('#login').hidden=true;$('#app').hidden=false;if(state.tenantId){const canAdvance=state.permissions.has('finder.module.advanced_search'),canSave=canAdvance&&state.permissions.has('finder.module.saved_search'),canRank=state.permissions.has('finder.module.opportunity_rank');$('#saved-searches').hidden=!canSave;if(canSave)await loadSaved();$('#toggle-advanced').hidden=!canAdvance;$('#top-opportunity').closest('article').hidden=!canRank;$('#sort option[value="opportunity"]').hidden=!canRank;}if(state.mode==='match')setStatus('Modo VGVmatch: a busca usa o VGVfinder. A associação com clientes será habilitada quando o CRM tenant-aware estiver disponível.');const query=parameters.get('q'),similar=parameters.get('similarTo');if(query){$('#natural-query').value=query;await search({text:query,offset:0,limit:state.limit});}else if(similar)await loadSimilar(similar);}
$('#login-form').addEventListener('submit',async(event)=>{event.preventDefault();if(state.tenantId){window.top.location.assign('/admin/finder');return;}const form=event.currentTarget,button=$('button',form);button.disabled=true;$('#login-error').textContent='';try{await api('/session',{method:'POST',body:{password:new FormData(form).get('password')}});await showApp();}catch(error){$('#login-error').textContent=error.message;}finally{button.disabled=false;}});
$('#logout').addEventListener('click',async()=>{try{await api(state.tenantId?'/api/v1/session':'/session',{method:'DELETE'});}finally{location.reload();}});
$('#toggle-advanced').addEventListener('click',(event)=>{const panel=$('#advanced-panel'),open=panel.hidden;panel.hidden=!open;event.currentTarget.setAttribute('aria-expanded',String(open));event.currentTarget.querySelector('span').textContent=open?'−':'+';});
$('#natural-form').addEventListener('submit',(event)=>{event.preventDefault();const text=$('#natural-query').value.trim(),source=safeUrl(text);if(source){previewListing(source);return;}if(text)search({text,offset:0,limit:state.limit});});

function previewFact(label,value){return value===null||value===undefined||value===''?null:el('span','',`${label}: ${value}`);}
function previewEvidence(result){const furnishing=result.furnishingObservation?.value==='furnished'?'Mobiliado':result.furnishingObservation?.value==='unfurnished'?'Não mobiliado':'Inconclusivo',occupancy=result.occupancyObservation?.value==='occupied'?'Ocupado':result.occupancyObservation?.value==='vacant'?'Desocupado':'Inconclusivo';return `Sugestão visual: mobília ${furnishing.toLowerCase()}; ocupação ${occupancy.toLowerCase()}. Confirme manualmente antes de cadastrar.`;}
function renderListingPreview(draft){state.preview=draft;const registration=$('#listing-registration');if(registration.open)registration.close();const section=$('#listing-preview'),media=el('div','listing-preview-media'),imageUrl=(draft.imageUrls||[]).map(safeImage).find(Boolean);if(imageUrl){const image=el('img');image.src=imageUrl;image.alt='';image.referrerPolicy='no-referrer';media.append(image);}else media.append(el('span','image-fallback','Imagem pública não disponível'));const body=el('div'),heading=el('p','eyebrow',`Prévia · ${draft.source?.name||'Fonte'}`),title=el('h2','',draft.title||'Anúncio sem título'),price=el('strong','',money(draft.askingPrice)),facts=el('div','listing-preview-facts'),message=el('p','listing-preview-message',draft.missingFields?.length?`Revise os campos não extraídos: ${draft.missingFields.join(', ')}.`:'Dados públicos extraídos. Nenhum registro foi gravado.');[previewFact('Cidade',draft.city),previewFact('Condomínio',draft.development),previewFact('Área',draft.areaM2==null?null:`${integer(draft.areaM2)} m²`),previewFact('Dormitórios',draft.bedrooms),previewFact('Suítes',draft.suites),previewFact('Vagas',draft.parkingSpaces)].filter(Boolean).forEach((item)=>facts.append(item));const actions=el('div','listing-preview-actions'),source=el('a','','Abrir anúncio'),review=el('button','','Revisar e cadastrar');source.href=draft.canonicalUrl;source.target='_blank';source.rel='noopener noreferrer';review.type='button';review.addEventListener('click',openListingRegistration);actions.append(source,review);if(draft.imageUrls?.length){const analyze=el('button','','Analisar imagens');analyze.type='button';analyze.addEventListener('click',()=>analyzePreviewImages(analyze,message));actions.append(analyze);}body.append(heading,title,price,facts,message,actions);section.replaceChildren(media,body);section.hidden=false;section.scrollIntoView({behavior:'smooth',block:'nearest'});}
async function previewListing(url){setBusy(true);$('#listing-preview').hidden=true;setStatus('Lendo o anúncio no Finder. Você permanecerá nesta tela e nenhum dado será gravado antes da revisão.');try{const draft=await api(exchangePath('/property-imports/preview'),{method:'POST',body:{url}});renderListingPreview(draft);setStatus('Anúncio encontrado. Confira a prévia abaixo antes de decidir se deseja revisar e cadastrar.');}catch(error){state.preview=null;const message=error.code==='property_source_not_found'?'O anúncio não foi encontrado no link informado. Confira o endereço e tente novamente.':error.message;setStatus(message,true);}finally{setBusy(false);}}
async function analyzePreviewImages(button,message){if(!state.preview?.imageUrls?.length)return;button.disabled=true;button.textContent='Analisando…';try{const result=await api(exchangePath('/market/properties/infer-images'),{method:'POST',body:{imageUrls:state.preview.imageUrls.slice(0,8),sourceReference:state.preview.canonicalUrl}});message.textContent=previewEvidence(result);}catch(error){message.textContent=error.code==='image_inference_unavailable'?'A análise visual ainda não está habilitada em produção. Revise as imagens manualmente; nenhuma classificação automática foi aplicada.':`Não foi possível analisar as imagens: ${error.message}.`;}finally{button.disabled=false;button.textContent='Analisar imagens';}}

const normalizedText=(value)=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const formNumber=(value)=>value===''?null:Number(value);
function setRegistrationValue(name,value){const field=$('#listing-registration-form').elements.namedItem(name);if(field&&value!==null&&value!==undefined)field.value=value;}
function updateRegistrationDevelopments(){const form=$('#listing-registration-form'),cityId=form.elements.cityId.value,developments=(state.locations?.developments||[]).filter((item)=>item.cityId===cityId),options=[new Option('Sem empreendimento',''),...developments.map((item)=>new Option(item.name,item.id))];if(state.preview?.development&&!developments.some((item)=>normalizedText(item.name)===normalizedText(state.preview.development)))options.push(new Option(`Cadastrar “${state.preview.development}”`,'__create__'));form.elements.developmentId.replaceChildren(...options);}
async function openListingRegistration(){if(!state.preview)return;const dialog=$('#listing-registration'),form=$('#listing-registration-form'),result=$('#listing-registration-result');$('#listing-registration-error').textContent='';try{if(!state.locations)state.locations=await api(exchangePath('/locations'));form.hidden=false;result.hidden=true;form.reset();form.elements.cityId.replaceChildren(new Option('Selecione a cidade',''),...state.locations.cities.map((item)=>new Option(item.name,item.id)));form.elements.regionId.replaceChildren(new Option('Sem região',''),...state.locations.regions.map((item)=>new Option(item.name,item.id)));const city=state.locations.cities.find((item)=>normalizedText(item.name)===normalizedText(state.preview.city));setRegistrationValue('propertyType',state.preview.propertyType||'other');setRegistrationValue('cityId',city?.id||'');updateRegistrationDevelopments();const development=state.locations.developments.find((item)=>item.cityId===city?.id&&normalizedText(item.name)===normalizedText(state.preview.development));setRegistrationValue('developmentId',development?.id||(state.preview.development?'__create__':''));for(const name of ['areaM2','bedrooms','suites','bathrooms','parkingSpaces','askingPrice','condoFee','propertyTax','title','description','canonicalUrl'])setRegistrationValue(name,state.preview[name]);setRegistrationValue('furnishing',state.preview.furnishingObservation?.value||'unknown');setRegistrationValue('occupancy',state.preview.occupancyObservation?.value||'unknown');dialog.showModal();}catch(error){setStatus(`Não foi possível preparar o cadastro: ${error.message}`,true);}}
function closeListingRegistration(){const dialog=$('#listing-registration');if(dialog.open)dialog.close();$('#listing-registration-error').textContent='';}
$('#listing-registration-form [name="cityId"]').addEventListener('change',updateRegistrationDevelopments);
$('#close-listing-registration').addEventListener('click',closeListingRegistration);
$('#cancel-listing-registration').addEventListener('click',closeListingRegistration);
$('#listing-registration').addEventListener('click',(event)=>{if(event.target===event.currentTarget)closeListingRegistration();});
$('#listing-registration-form').addEventListener('submit',async(event)=>{event.preventDefault();const form=event.currentTarget,draft=state.preview,button=$('button[type="submit"]',form),city=state.locations?.cities.find((item)=>item.id===form.elements.cityId.value);if(!draft||!city)return;const stateRow=state.locations.states.find((item)=>item.id===city.stateId),country=stateRow&&state.locations.countries.find((item)=>item.id===stateRow.countryId),area=formNumber(form.elements.areaM2.value),propertyType=form.elements.propertyType.value,error=$('#listing-registration-error'),developmentValue=form.elements.developmentId.value;if(!stateRow||!country||!area||area<=0){error.textContent='Revise cidade e área antes de cadastrar.';return;}const observedAt=new Date().toISOString(),observation=(value,kind)=>value==='unknown'?null:{value,assertionStatus:'verified',sourceReference:draft.canonicalUrl,observedAt,rawEvidence:`${kind} confirmado manualmente durante a revisão no VGVfinder.`,metadata:{humanReviewedAt:observedAt}},payload={countryId:country.id,stateId:stateRow.id,cityId:city.id,regionId:form.elements.regionId.value||null,developmentId:developmentValue&&developmentValue!=='__create__'?developmentValue:null,developmentName:developmentValue==='__create__'?draft.development:null,propertyType,privateAreaM2:propertyType==='apartment'?area:null,builtAreaM2:propertyType==='apartment'?null:area,bedrooms:formNumber(form.elements.bedrooms.value),suites:formNumber(form.elements.suites.value),bathrooms:formNumber(form.elements.bathrooms.value),parkingSpaces:formNumber(form.elements.parkingSpaces.value),imageUrls:[...(draft.imageUrls||[])],furnishingObservation:observation(form.elements.furnishing.value,'Mobília'),occupancyObservation:observation(form.elements.occupancy.value,'Ocupação'),sourceGeography:draft.sourceGeography,listing:{source:{host:draft.source.host},externalListingId:draft.externalListingId,url:draft.canonicalUrl,canonicalUrl:draft.canonicalUrl,title:form.elements.title.value.trim()||null,description:form.elements.description.value.trim()||null,askingPrice:formNumber(form.elements.askingPrice.value),condoFee:formNumber(form.elements.condoFee.value),propertyTax:formNumber(form.elements.propertyTax.value),transactionType:'sale',rawCity:draft.city,rawDevelopment:draft.development,rawPayload:{extraction:draft.rawExtraction,missingFields:draft.missingFields,reviewedFields:true}}};if(!payload.listing.askingPrice||payload.listing.askingPrice<=0){error.textContent='Informe um preço anunciado válido.';return;}button.disabled=true;button.textContent='Gravando…';error.textContent='';try{const result=await api(exchangePath('/properties'),{method:'POST',body:payload});renderRegistrationResult(result.id);}catch(caught){error.textContent=caught.message;}finally{button.disabled=false;button.textContent='Cadastrar no Data Core';}});
function renderRegistrationResult(propertyId){const dialog=$('#listing-registration'),form=$('#listing-registration-form'),result=$('#listing-registration-result'),title=el('h3','','Imóvel disponível no Data Core'),text=el('p','',`VGV Property ID: ${propertyId}`),actions=el('div','listing-preview-actions'),intel=el('a','','Analisar no VGVintel'),similar=el('button','','Buscar similares no Finder');intel.href=state.tenantId?`/admin/intelligence?tenant=${encodeURIComponent(state.tenantId)}&propertyId=${encodeURIComponent(propertyId)}`:`/intel/?propertyId=${encodeURIComponent(propertyId)}`;intel.target='_top';similar.type='button';similar.addEventListener('click',async()=>{dialog.close();await loadSimilar(propertyId);});actions.append(intel,similar);result.replaceChildren(title,text,actions);form.hidden=true;result.hidden=false;setStatus('Cadastro concluído. O imóvel já pode ser pesquisado e analisado no VGVintel.');}

function range(min,max){const value={};if(min!=='')value.min=Number(min);if(max!=='')value.max=Number(max);return Object.keys(value).length?{mode:'hard',value}:undefined;}
function manualRequest(form){const data=new FormData(form),criteria={},location=String(data.get('location')||'').trim();if(data.get('propertyType'))criteria.propertyType={mode:'hard',value:data.get('propertyType')};for(const [field,min,max] of [['price','priceMin','priceMax'],['area','areaMin','areaMax'],['lotArea','lotMin','lotMax']]){const value=range(String(data.get(min)||''),String(data.get(max)||''));if(value)criteria[field]=value;}for(const field of ['bedrooms','suites','bathrooms','parking']){const value=String(data.get(field)||'');if(value!=='')criteria[field]={mode:'hard',value:{min:Number(value)}};}if(data.get('furnishing'))criteria.furnishing={mode:'hard',value:data.get('furnishing')};for(const key of ['pool','air_conditioning','balcony','automation','forest_view']){const value=data.get(key);if(value!=='')criteria.features=(criteria.features||[]).concat({mode:'hard',value:{key,value:value==='true'}});}return {text:location||undefined,criteria,offset:0,limit:state.limit};}
$('#advanced-panel').addEventListener('submit',(event)=>{event.preventDefault();search(manualRequest(event.currentTarget));});

async function search(request){state.offset=request.offset||0;state.lastRequest={...request};setBusy(true);setStatus('Consultando inventário ativo, comparáveis e evidências de preço...');try{const data=await api(finderPath('/search'),{method:'POST',body:request});state.data=data;render(data);if(data.clarification?.required){const details=[...(data.clarification.ambiguities||[]),...(data.clarification.unparsedFragments||[])].join(' · ');setStatus(`Busca executada com pontos para revisão: ${details}.${enrichmentStatus(data)}`);}else setStatus(`${data.resultCount??data.items?.length??0} imóvel(is) encontrado(s) no Data Core. Preços são valores pedidos, não avaliações.${enrichmentStatus(data)}`);}catch(error){setStatus(error.message,true);$('#rankings').hidden=true;$('#results').hidden=true;}finally{setBusy(false);$('#save-search').disabled=!state.tenantId||Object.keys(structuredCriteria()).length===0;}}

function propertyOf(row){return row?.item||row?.property||row;}
function propertyType(value){return {house:'Casa',apartment:'Apartamento',land:'Terreno',commercial:'Comercial',other:'Imóvel'}[value]||'Imóvel';}
function title(item){return [item.development,item.region,item.city].filter(Boolean).join(' · ')||`${propertyType(item.propertyType)} ${item.propertyId?.slice(0,8)||''}`;}
function miniRow(row,index,metric){const item=propertyOf(row),node=el('div','mini');node.append(el('b','',`#${index+1}`),el('span','',title(item)),el('b','',metric==='ppm'?(item.pricePerM2==null?'—':`${money(item.pricePerM2)}/m²`):metric==='opportunity'?(row.opportunity?.score==null?'—':`${row.opportunity.score}/100`):money(item.askingPrice)));return node;}
function renderTop(target,rows,metric){const node=$(target);node.replaceChildren(...(rows?.length?rows.map((row,index)=>miniRow(row,index,metric)):[el('p','match-note','Evidência insuficiente para este ranking.') ]));}
function image(item){const frame=el('div','property-media'),source=(item.imageUrls||[]).map(safeImage).find(Boolean);if(!source){frame.append(el('span','image-fallback','Imagem não disponível'));return frame;}const image=el('img');image.src=source;image.alt='';image.loading='lazy';image.referrerPolicy='no-referrer';image.addEventListener('error',()=>frame.replaceChildren(el('span','image-fallback','Imagem não disponível')),{once:true});frame.append(image);return frame;}
function action(href,label,primary=false){const link=el('a',primary?'primary':'',label),url=new URL(href,location.origin),module=url.pathname.startsWith('/intel/')?'intelligence':url.pathname.startsWith('/exchange/')?'exchange':null;if(state.tenantId&&module){url.searchParams.set('tenant',state.tenantId);link.href=`/admin/${module}?${url.searchParams}`;link.target='_top';}else link.href=href;return link;}
function finderLink(values){const query=new URLSearchParams(values);if(state.tenantId)query.set('tenantId',state.tenantId);return `/finder/?${query}`;}
function tri(value){return value===true?'Sim':value===false?'Não':'Desconhecido';}
function card(row){const item=propertyOf(row),article=el('article','property');const main=el('div','property-main');main.append(el('span','source',`${item.sourceName||'Fonte'} · captura ${new Date(item.lastSeenAt).toLocaleDateString('pt-BR')}`),el('h3','',title(item)),el('p','',`${propertyType(item.propertyType)} · VGV ID ${item.propertyId}`));const facts=el('div','facts');[[item.area==null?'Área desconhecida':`${integer(item.area)} m²`],[`Dormitórios: ${integer(item.bedrooms)}`],[`Suítes: ${integer(item.suites)}`],[`Vagas: ${integer(item.parking)}`]].forEach(([text])=>facts.append(el('span','',text)));main.append(facts);const characteristics=el('div','facts');for(const [key,label] of Object.entries({pool:'Piscina',solar_energy:'Energia fotovoltaica',air_conditioning:'Ar-condicionado',balcony:'Varanda',automation:'Automação',forest_view:'Vista para mata'}))characteristics.append(el('span','',`${label}: ${tri(item.features?.[key])}`));characteristics.append(el('span','',`Mobiliado: ${item.furnishing==='furnished'?'Sim':item.furnishing==='unfurnished'?'Não':'Desconhecido'}`));main.append(characteristics);const metrics=el('div','property-metrics');metrics.append(el('strong','',money(item.askingPrice)),el('span','',item.pricePerM2==null?'R$/m²: Desconhecido':`${money(item.pricePerM2)}/m²`));const scores=el('div','scores');scores.append(el('span','score',`Match: ${row.matchScore==null?'Desconhecido':`${row.matchScore}/100`}`));if(row.opportunity?.score!=null)scores.append(el('span','score opportunity',`Oportunidade: ${row.opportunity.score}/100`));const confidence=row.confidenceScore??row.opportunity?.confidence;if(confidence!=null)scores.append(el('span','score',`Confiança: ${confidence}/100`));metrics.append(scores);const explanation=el('ul','explain');(row.explanations||row.opportunity?.explanations||[]).slice(0,3).forEach((text)=>explanation.append(el('li','',text)));metrics.append(explanation);const actions=el('div','property-actions');actions.append(action(`/intel/?propertyId=${encodeURIComponent(item.propertyId)}`,'Avaliar no VGVintel',true),action(`/exchange/?subjectPropertyId=${encodeURIComponent(item.propertyId)}`,'Analisar no VGVexchange'),action(finderLink({similarTo:item.propertyId}),'Buscar similares'),action(finderLink({mode:'match',propertyId:item.propertyId}),'Encontrar clientes'));const source=safeUrl(item.sourceUrl);if(source)actions.append(action(source,'Abrir anúncio ↗'));article.append(image(item),main,metrics,actions);return article;}
function sortedItems(){const items=[...(state.data?.items||[])],sort=$('#sort').value;if(sort==='price')items.sort((a,b)=>propertyOf(a).askingPrice-propertyOf(b).askingPrice);if(sort==='ppm')items.sort((a,b)=>(propertyOf(a).pricePerM2??Infinity)-(propertyOf(b).pricePerM2??Infinity));if(sort==='opportunity')items.sort((a,b)=>(b.opportunity?.score??-1)-(a.opportunity?.score??-1));return items;}
function render(data){$('#rankings').hidden=false;$('#results').hidden=false;renderTop('#top-opportunity',data.top5?.opportunities,'opportunity');renderTop('#top-price',data.top5?.lowestPrice,'price');renderTop('#top-ppm',data.top5?.lowestPricePerM2,'ppm');$('#result-count').textContent=`${data.resultCount??data.items?.length??0} imóveis encontrados`;$('#result-list').replaceChildren(...(sortedItems().length?sortedItems().map(card):[el('div','status','Nenhum imóvel atende aos critérios conhecidos.') ]));$('#previous').disabled=state.offset===0;$('#next').disabled=!data.page?.hasMore;$('#page-label').textContent=`Resultados ${state.offset+1}–${state.offset+(data.items?.length||0)}`;}
$('#sort').addEventListener('change',()=>{if(state.data)$('#result-list').replaceChildren(...sortedItems().map(card));});
$('#previous').addEventListener('click',()=>{if(state.lastRequest)search({...state.lastRequest,offset:Math.max(0,state.offset-state.limit)});});
$('#next').addEventListener('click',()=>{if(state.lastRequest)search({...state.lastRequest,offset:state.offset+state.limit});});

async function loadSimilar(id){setBusy(true);setStatus('Buscando imóveis semelhantes com tolerância inicial de área de ±10%...');try{const data=await api(`${finderPath(`/similar/${encodeURIComponent(id)}`)}?tolerance=0.1&limit=20`),items=(data.items||[]).map((row)=>({item:row.property,matchScore:row.similarity?.score,opportunity:null,confidenceScore:null,explanations:row.similarity?.explanation||[]}));state.data={items,resultCount:items.length,page:{hasMore:false},top5:{lowestPrice:[],lowestPricePerM2:[],opportunities:[]}};state.offset=0;render(state.data);$('#rankings').hidden=true;setStatus(`${items.length} imóvel(is) semelhante(s), priorizando condomínio, região e área ±10%.`);}catch(error){setStatus(error.message,true);}finally{setBusy(false);}}

async function loadSaved(){try{state.saved=(await api(finderPath('/saved-searches'))).items||[];renderSaved();}catch(error){setStatus(error.message,true);}}
function renderSaved(){const list=$('#saved-search-list');list.replaceChildren(...(state.saved.length?state.saved.map((item)=>{const node=el('article','saved-item'),actions=el('div');actions.append(el('button','', 'Aplicar'),el('button','quiet','Renomear'),el('button','delete','Excluir'));actions.children[0].addEventListener('click',()=>search({criteria:item.criteria,offset:0,limit:state.limit}));actions.children[1].addEventListener('click',()=>renameSaved(item));actions.children[2].addEventListener('click',()=>deleteSaved(item));node.append(el('strong','',item.name),actions);return node;}):[el('p','match-note','Nenhuma busca salva.') ]));}
$('#save-search-form').addEventListener('submit',async(event)=>{event.preventDefault();const criteria=structuredCriteria();if(!Object.keys(criteria).length)return;const form=event.currentTarget;try{await api(finderPath('/saved-searches'),{method:'POST',body:{name:new FormData(form).get('name'),criteria}});form.reset();await loadSaved();}catch(error){setStatus(error.message,true);}});
async function renameSaved(item){const name=window.prompt('Novo nome da busca',item.name);if(!name?.trim())return;try{await api(finderPath(`/saved-searches/${item.id}`),{method:'PUT',body:{name:name.trim(),criteria:item.criteria}});await loadSaved();}catch(error){setStatus(error.message,true);}}
async function deleteSaved(item){if(!window.confirm(`Excluir a busca “${item.name}”?`))return;try{await api(finderPath(`/saved-searches/${item.id}`),{method:'DELETE'});await loadSaved();}catch(error){setStatus(error.message,true);}}

boot();
