import '/shared/vgv-command.js?v=20260821-1';
const API='https://permuta-api.vgventures.com.br',IMAGE_HOSTS=new Set(['imgbr.imovelwebcdn.com','si9dados3.com.br']);
const state={offset:0,limit:20,lastRequest:null,data:null,mode:new URLSearchParams(location.search).get('mode')||'search'};
const $=(selector,root=document)=>root.querySelector(selector);
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=String(text);return node;}
function finite(value){const number=Number(value);return value!==null&&value!==''&&Number.isFinite(number)?number:null;}
const money=(value)=>finite(value)===null?'Não informado':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(value);
const integer=(value)=>finite(value)===null?'?':new Intl.NumberFormat('pt-BR').format(value);
function safeUrl(value){try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password?url.href:null;}catch{return null;}}
function safeImage(value){const url=safeUrl(value);return url&&IMAGE_HOSTS.has(new URL(url).hostname.toLowerCase())?url:null;}
async function api(path,options={}){let response;try{response=await fetch(`${API}${path}`,{credentials:'include',method:options.method||'GET',headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{})},body:options.body?JSON.stringify(options.body):undefined});}catch{throw new Error('Não foi possível conectar ao serviço.');}let data=null;try{data=await response.json();}catch{}if(!response.ok)throw new Error(data?.error?.message||data?.error||`Erro ${response.status}`);return data;}
function setStatus(message,error=false){const box=$('#status');box.textContent=message;box.classList.toggle('error',error);}
function setBusy(busy){document.querySelectorAll('button').forEach((button)=>{if(button.id!=='logout')button.disabled=busy;});}

async function boot(){try{if((await api('/session')).authenticated)return showApp();}catch{}$('#login').hidden=false;}
async function showApp(){$('#login').hidden=true;$('#app').hidden=false;if(state.mode==='match')setStatus('Modo VGVmatch: a busca usa o VGVfinder. A associação com clientes será habilitada quando o CRM tenant-aware estiver disponível.');const params=new URLSearchParams(location.search),query=params.get('q'),similar=params.get('similarTo');if(query){$('#natural-query').value=query;await search({text:query,offset:0,limit:state.limit});}else if(similar)await loadSimilar(similar);}
$('#login-form').addEventListener('submit',async(event)=>{event.preventDefault();const form=event.currentTarget,button=$('button',form);button.disabled=true;$('#login-error').textContent='';try{await api('/session',{method:'POST',body:{password:new FormData(form).get('password')}});await showApp();}catch(error){$('#login-error').textContent=error.message;}finally{button.disabled=false;}});
$('#logout').addEventListener('click',async()=>{try{await api('/session',{method:'DELETE'});}finally{location.reload();}});
$('#toggle-advanced').addEventListener('click',(event)=>{const panel=$('#advanced-panel'),open=panel.hidden;panel.hidden=!open;event.currentTarget.setAttribute('aria-expanded',String(open));event.currentTarget.querySelector('span').textContent=open?'−':'+';});
$('#natural-form').addEventListener('submit',(event)=>{event.preventDefault();const text=$('#natural-query').value.trim();if(text)search({text,offset:0,limit:state.limit});});

function range(min,max){const value={};if(min!=='')value.min=Number(min);if(max!=='')value.max=Number(max);return Object.keys(value).length?{mode:'hard',value}:undefined;}
function manualRequest(form){const data=new FormData(form),criteria={},location=String(data.get('location')||'').trim();if(data.get('propertyType'))criteria.propertyType={mode:'hard',value:data.get('propertyType')};for(const [field,min,max] of [['price','priceMin','priceMax'],['area','areaMin','areaMax'],['lotArea','lotMin','lotMax']]){const value=range(String(data.get(min)||''),String(data.get(max)||''));if(value)criteria[field]=value;}for(const field of ['bedrooms','suites','bathrooms','parking']){const value=String(data.get(field)||'');if(value!=='')criteria[field]={mode:'hard',value:{min:Number(value)}};}if(data.get('furnishing'))criteria.furnishing={mode:'hard',value:data.get('furnishing')};for(const key of ['pool','air_conditioning','balcony','automation','forest_view']){const value=data.get(key);if(value!=='')criteria.features=(criteria.features||[]).concat({mode:'hard',value:{key,value:value==='true'}});}return {text:location||undefined,criteria,offset:0,limit:state.limit};}
$('#advanced-panel').addEventListener('submit',(event)=>{event.preventDefault();search(manualRequest(event.currentTarget));});

async function search(request){state.offset=request.offset||0;state.lastRequest={...request};setBusy(true);setStatus('Consultando inventário ativo, comparáveis e evidências de preço...');try{const data=await api('/api/v1/market/finder/search',{method:'POST',body:request});state.data=data;render(data);if(data.clarification?.required){const details=[...(data.clarification.ambiguities||[]),...(data.clarification.unparsedFragments||[])].join(' · ');setStatus(`Busca executada com pontos para revisão: ${details}`);}else setStatus(`${data.resultCount??data.items?.length??0} imóvel(is) encontrado(s). Preços são valores pedidos, não avaliações.`);}catch(error){setStatus(error.message,true);$('#rankings').hidden=true;$('#results').hidden=true;}finally{setBusy(false);}}

function propertyOf(row){return row?.item||row?.property||row;}
function title(item){return [item.development,item.region,item.city].filter(Boolean).join(' · ')||`${item.propertyType||'Imóvel'} ${item.propertyId?.slice(0,8)||''}`;}
function miniRow(row,index,metric){const item=propertyOf(row),node=el('div','mini');node.append(el('b','',`#${index+1}`),el('span','',title(item)),el('b','',metric==='ppm'?(item.pricePerM2==null?'—':`${money(item.pricePerM2)}/m²`):metric==='opportunity'?(row.opportunity?.score==null?'—':`${row.opportunity.score}/100`):money(item.askingPrice)));return node;}
function renderTop(target,rows,metric){const node=$(target);node.replaceChildren(...(rows?.length?rows.map((row,index)=>miniRow(row,index,metric)):[el('p','match-note','Evidência insuficiente para este ranking.') ]));}
function image(item){const frame=el('div','property-media'),source=(item.imageUrls||[]).map(safeImage).find(Boolean);if(!source){frame.append(el('span','image-fallback','Imagem não disponível'));return frame;}const image=el('img');image.src=source;image.alt='';image.loading='lazy';image.referrerPolicy='no-referrer';image.addEventListener('error',()=>frame.replaceChildren(el('span','image-fallback','Imagem não disponível')),{once:true});frame.append(image);return frame;}
function action(href,label,primary=false){const link=el('a',primary?'primary':'',label);link.href=href;return link;}
function card(row){const item=propertyOf(row),article=el('article','property');const main=el('div','property-main');main.append(el('span','source',`${item.sourceName||'Fonte'} · captura ${new Date(item.lastSeenAt).toLocaleDateString('pt-BR')}`),el('h3','',title(item)),el('p','',`${item.propertyType||'Imóvel'} · VGV ID ${item.propertyId}`));const facts=el('div','facts');[[item.area==null?'Área desconhecida':`${integer(item.area)} m²`,null],[`${integer(item.bedrooms)} dorm.`,null],[`${integer(item.suites)} suítes`,null],[`${integer(item.parking)} vagas`,null]].forEach(([text])=>facts.append(el('span','',text)));main.append(facts);const metrics=el('div','property-metrics');metrics.append(el('strong','',money(item.askingPrice)),el('span','',item.pricePerM2==null?'R$/m² desconhecido':`${money(item.pricePerM2)}/m²`));const scores=el('div','scores');scores.append(el('span','score',`Match ${row.matchScore==null?'—':`${row.matchScore}/100`}`),el('span','score opportunity',`Oportunidade ${row.opportunity?.score==null?'—':`${row.opportunity.score}/100`}`),el('span','score',`Confiança ${row.confidenceScore??row.opportunity?.confidence??'—'}/100`));metrics.append(scores);const explanation=el('ul','explain');(row.explanations||row.opportunity?.explanations||[]).slice(0,3).forEach((text)=>explanation.append(el('li','',text)));metrics.append(explanation);const actions=el('div','property-actions');actions.append(action(`/intel/?propertyId=${encodeURIComponent(item.propertyId)}`,'Avaliar no VGVintel',true),action(`/exchange/?subjectPropertyId=${encodeURIComponent(item.propertyId)}`,'Analisar no VGVexchange'),action(`/finder/?similarTo=${encodeURIComponent(item.propertyId)}`,'Buscar similares'),action(`/finder/?mode=match&propertyId=${encodeURIComponent(item.propertyId)}`,'Encontrar clientes'));const source=safeUrl(item.sourceUrl);if(source)actions.append(action(source,'Abrir anúncio ↗'));article.append(image(item),main,metrics,actions);return article;}
function sortedItems(){const items=[...(state.data?.items||[])],sort=$('#sort').value;if(sort==='price')items.sort((a,b)=>propertyOf(a).askingPrice-propertyOf(b).askingPrice);if(sort==='ppm')items.sort((a,b)=>(propertyOf(a).pricePerM2??Infinity)-(propertyOf(b).pricePerM2??Infinity));if(sort==='opportunity')items.sort((a,b)=>(b.opportunity?.score??-1)-(a.opportunity?.score??-1));return items;}
function render(data){$('#rankings').hidden=false;$('#results').hidden=false;renderTop('#top-opportunity',data.top5?.opportunities,'opportunity');renderTop('#top-price',data.top5?.lowestPrice,'price');renderTop('#top-ppm',data.top5?.lowestPricePerM2,'ppm');$('#result-count').textContent=`${data.resultCount??data.items?.length??0} imóveis encontrados`;$('#result-list').replaceChildren(...(sortedItems().length?sortedItems().map(card):[el('div','status','Nenhum imóvel atende aos critérios conhecidos.') ]));$('#previous').disabled=state.offset===0;$('#next').disabled=!data.page?.hasMore;$('#page-label').textContent=`Resultados ${state.offset+1}–${state.offset+(data.items?.length||0)}`;}
$('#sort').addEventListener('change',()=>{if(state.data)$('#result-list').replaceChildren(...sortedItems().map(card));});
$('#previous').addEventListener('click',()=>{if(state.lastRequest)search({...state.lastRequest,offset:Math.max(0,state.offset-state.limit)});});
$('#next').addEventListener('click',()=>{if(state.lastRequest)search({...state.lastRequest,offset:state.offset+state.limit});});

async function loadSimilar(id){setBusy(true);setStatus('Buscando imóveis semelhantes com tolerância inicial de área de ±10%...');try{const data=await api(`/api/v1/market/finder/similar/${encodeURIComponent(id)}?tolerance=0.1&limit=20`),items=(data.items||[]).map((row)=>({item:row.property,matchScore:row.similarity?.score,opportunity:null,confidenceScore:null,explanations:row.similarity?.explanation||[]}));state.data={items,resultCount:items.length,page:{hasMore:false},top5:{lowestPrice:[],lowestPricePerM2:[],opportunities:[]}};state.offset=0;render(state.data);$('#rankings').hidden=true;setStatus(`${items.length} imóvel(is) semelhante(s), priorizando condomínio, região e área ±10%.`);}catch(error){setStatus(error.message,true);}finally{setBusy(false);}}

boot();
